### Admin

# Article
admin_create_article:
    path: /api/admin/articles
    controller: App\Article\Infrastructure\Http\Admin\Article\CreateArticleController::execute
    methods: POST

admin_get_article:
    path: /api/admin/articles/{id}
    controller: App\Article\Infrastructure\Http\Admin\Article\GetArticleController::execute
    methods: GET

admin_update_article:
    path: /api/admin/articles/{id}
    controller: App\Article\Infrastructure\Http\Admin\Article\UpdateArticleController::execute
    methods: PATCH
# Article

### Admin
